In [3]:
import requests 
from lxml import html 
import csv
import pandas as pd

In [4]:
r = requests.get('https://www.basketball-reference.com/leagues/NBA_2019_per_game.html')
data = html.fromstring(r.text)

In [9]:
#combines all the columns
nba2019 = zip(player, 
              position, 
              age, 
              team, 
              games, 
              games_started, 
              mins_per_g, 
              fg_per_g, 
              fga_per_g, 
              fg_pct, 
              fg3_per_g, 
              fg3a_per_g, 
              fg3_pct, 
              fg2_per_g, 
              fg2a_per_g, 
              fg2_pct, 
              efg_pct, 
              ft_per_g, 
              fta_per_g, 
              ft_pct, 
              orb_per_g, 
              drb_per_g,
              trb_per_g,
              ast_per_g,
              stl_per_g,
              blk_per_g,
              tov_per_g,
              pf_per_g,
              pts_per_g)
#organizing our data structure to a pandas dataframe
df = pd.DataFrame(nba2019)

df.head()

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,Álex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,.357,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,.222,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,.345,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,.595,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,.576,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9

In [13]:
#renaming the column names 
df = df.rename(columns = {0:'player', 
                          1:'position', 
                          2:'age', 
                          3:'team', 
                          4:'games', 
                          5:'games_started', 
                          6:'mins_per_g', 
                          7:'fg_per_g', 
                          8:'fga_per_g', 
                          9:'fg_pct', 
                          10:'fg3_per_g', 
                          11:'fg3a_per_g', 
                          12:'fg3_pct', 
                          13:'fg2_per_g', 
                          14:'fg2a_per_g', 
                          15:'fg2_pct', 
                          16:'efg_pct', 
                          17:'ft_per_g', 
                          18:'fta_per_g', 
                          19:'ft_pct', 
                          20:'orb_per_g', 
                          21:'drb_per_g',
                          22:'trb_per_g',
                          23:'ast_per_g',
                          24:'stl_per_g',
                          25:'blk_per_g',
                          26:'tov_per_g',
                          27:'pf_per_g',
                          28:'pts_per_g'})
df.head()

,player,position,age,team,games,games_started,mins_per_g,fg_per_g,fga_per_g,fg_pct,...,ft_pct,orb_per_g,drb_per_g,trb_per_g,ast_per_g,stl_per_g,blk_per_g,tov_per_g,pf_per_g,pts_per_g
0,Álex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,.357,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,.222,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,.345,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,.595,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,.576,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9

In [7]:
#The types were not numeric, so we changed them to a numeric format to perform analytics
df['age'] = pd.to_numeric(df['age'])
df['age'].fillna(0, inplace=True)

df['games'] = pd.to_numeric(df['games'])
df['games'].fillna(0, inplace=True)

df['games_started'] = pd.to_numeric(df['games_started'])
df['games_started'].fillna(0, inplace=True)

df['mins_per_g'] = pd.to_numeric(df['mins_per_g'])
df['mins_per_g'].fillna(0, inplace=True)

df['fg_per_g'] = pd.to_numeric(df['fg_per_g'])
df['fg_per_g'].fillna(0, inplace=True)

df['fga_per_g'] = pd.to_numeric(df['fga_per_g'])
df['fga_per_g'].fillna(0, inplace=True)

df['fg_pct'] = pd.to_numeric(df['fg_pct'])
df['fg_pct'].fillna(0, inplace=True)

df['fg3_per_g'] = pd.to_numeric(df['fg3_per_g'])
df['fg3_per_g'].fillna(0, inplace=True)

df['fg3a_per_g'] = pd.to_numeric(df['fg3a_per_g'])
df['fg3a_per_g'].fillna(0, inplace=True)

df['fg3_pct'] = pd.to_numeric(df['fg3_pct'])
df['fg3_pct'].fillna(0, inplace=True)

df['fg2_per_g'] = pd.to_numeric(df['fg2_per_g'])
df['fg2_per_g'].fillna(0, inplace=True)

df['fg2a_per_g'] = pd.to_numeric(df['fg2a_per_g'])
df['fg2a_per_g'].fillna(0, inplace=True)

df['fg2_pct'] = pd.to_numeric(df['fg2_pct'])
df['fg2_pct'].fillna(0, inplace=True)

df['efg_pct'] = pd.to_numeric(df['efg_pct'])
df['efg_pct'].fillna(0, inplace=True)

df['ft_per_g'] = pd.to_numeric(df['ft_per_g'])
df['ft_per_g'].fillna(0, inplace=True)

df['fta_per_g'] = pd.to_numeric(df['fta_per_g'])
df['fta_per_g'].fillna(0, inplace=True)

df['ft_pct'] = pd.to_numeric(df['ft_pct'])
df['ft_pct'].fillna(0, inplace=True)

df['orb_per_g'] = pd.to_numeric(df['orb_per_g'])
df['orb_per_g'].fillna(0, inplace=True)

df['drb_per_g'] = pd.to_numeric(df['drb_per_g'])
df['drb_per_g'].fillna(0, inplace=True)

df['trb_per_g'] = pd.to_numeric(df['trb_per_g'])
df['trb_per_g'].fillna(0, inplace=True)

df['ast_per_g'] = pd.to_numeric(df['ast_per_g'])
df['ast_per_g'].fillna(0, inplace=True)

df['stl_per_g'] = pd.to_numeric(df['stl_per_g'])
df['stl_per_g'].fillna(0, inplace=True)

df['blk_per_g'] = pd.to_numeric(df['blk_per_g'])
df['blk_per_g'].fillna(0, inplace=True)

df['tov_per_g'] = pd.to_numeric(df['tov_per_g'])
df['tov_per_g'].fillna(0, inplace=True)

df['pf_per_g'] = pd.to_numeric(df['pf_per_g'])
df['pf_per_g'].fillna(0, inplace=True)

df['pts_per_g'] = pd.to_numeric(df['pts_per_g'])
df['pts_per_g'].fillna(0, inplace=True)

df.info()

KeyError: 'age'

In [14]:
#there were duplicate players, so we had to clean it 
stats = df.drop_duplicates(subset=['player'], keep=False)

stats.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 444 entries, 0 to 704
Data columns (total 29 columns):
player           444 non-null object
position         444 non-null object
age              444 non-null object
team             444 non-null object
games            444 non-null object
games_started    444 non-null object
mins_per_g       444 non-null object
fg_per_g         444 non-null object
fga_per_g        444 non-null object
fg_pct           444 non-null object
fg3_per_g        444 non-null object
fg3a_per_g       444 non-null object
fg3_pct          444 non-null object
fg2_per_g        444 non-null object
fg2a_per_g       444 non-null object
fg2_pct          444 non-null object
efg_pct          444 non-null object
ft_per_g         444 non-null object
fta_per_g        444 non-null object
ft_pct           444 non-null object
orb_per_g        444 non-null object
drb_per_g        444 non-null object
trb_per_g        444 non-null object
ast_per_g        444 non-null object
stl_per_g        444 non-null object
blk_per_g        444 non-null object
tov_per_g        444 non-null object
pf_per_g         444 non-null object
pts_per_g        444 non-null object
dtypes: object(29)
memory usage: 104.1+ KB

In [62]:
stats.head()

,player,position,age,team,games,games_started,mins_per_g,fg_per_g,fga_per_g,fg_pct,...,ft_pct,orb_per_g,drb_per_g,trb_per_g,ast_per_g,stl_per_g,blk_per_g,tov_per_g,pf_per_g,pts_per_g
0,Álex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,.357,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,.222,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,.345,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,.595,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,.576,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9

In [64]:
stats.columns

Index(['player', 'position', 'age', 'team', 'games', 'games_started',
       'mins_per_g', 'fg_per_g', 'fga_per_g', 'fg_pct', 'fg3_per_g',
       'fg3a_per_g', 'fg3_pct', 'fg2_per_g', 'fg2a_per_g', 'fg2_pct',
       'efg_pct', 'ft_per_g', 'fta_per_g', 'ft_pct', 'orb_per_g', 'drb_per_g',
       'trb_per_g', 'ast_per_g', 'stl_per_g', 'blk_per_g', 'tov_per_g',
       'pf_per_g', 'pts_per_g'],
      dtype='object')

In [66]:
stats['position'].describe()

count     444
unique      5
top        SG
freq      116
Name: position, dtype: object

In [2]:
position = stats.groupby(['position']).mean()

NameError: name 'stats' is not defined