In [1]:
import requests 
from lxml import html 
import csv
import pandas as pd

In [2]:
#visit the webpage and access the web contents
r = requests.get('https://www.basketball-reference.com/leagues/NBA_2019_per_game.html')
data = html.fromstring(r.text)

In [3]:
player = data.xpath("//tbody/tr/td[@data-stat='player']/a[@href]/text()")
position = data.xpath("//tbody/tr/td[@class='center ']/text()")
age = data.xpath("//tbody/tr/td[@data-stat='age']/text()")
team = data.xpath("//tbody/tr/td[@data-stat='team_id']/a[@href]/text()|//tbody/tr/td[@data-stat='team_id']/text()")
games = data.xpath("//tbody/tr/td[@data-stat='g']/text()")
games_started = data.xpath("//tbody/tr/td[@data-stat='gs']/text()")
mins_per_g = data.xpath("//tbody/tr/td[@data-stat='mp_per_g']/text()")
fg_per_g = data.xpath("//tbody/tr/td[@data-stat='fg_per_g']/text()")
fga_per_g = data.xpath("//tbody/tr/td[@data-stat='fga_per_g']/text()")
fg_pct = data.xpath("//tbody/tr/td[@data-stat='fg_pct']")
fg_pct = [i.text_content() for i in fg_pct]
fg3_per_g = data.xpath("//tbody/tr/td[@data-stat='fg3_per_g']/text()")
fg3a_per_g = data.xpath("//tbody/tr/td[@data-stat='fg3a_per_g']/text()")
fg3_pct = data.xpath("//tbody/tr/td[@data-stat='fg3_pct']")
fg3_pct = [i.text_content() for i in fg3_pct]
fg2_per_g = data.xpath("//tbody/tr/td[@data-stat='fg2_per_g']/text()")
fg2a_per_g = data.xpath("//tbody/tr/td[@data-stat='fg2a_per_g']/text()")
fg2_pct = data.xpath("//tbody/tr/td[@data-stat='fg2_pct']")
fg2_pct = [i.text_content() for i in fg2_pct]
efg_pct = data.xpath("//tbody/tr/td[@data-stat='efg_pct']")
efg_pct = [i.text_content() for i in efg_pct]
ft_per_g = data.xpath("//tbody/tr/td[@data-stat='ft_per_g']/text()")
fta_per_g = data.xpath("//tbody/tr/td[@data-stat='ft_per_g']/text()")
ft_pct = data.xpath("//tbody/tr/td[@data-stat='ft_pct']")
ft_pct = [i.text_content() for i in ft_pct]
orb_per_g = data.xpath("//tbody/tr/td[@data-stat='orb_per_g']/text()")
drb_per_g = data.xpath("//tbody/tr/td[@data-stat='drb_per_g']/text()")
trb_per_g = data.xpath("//tbody/tr/td[@data-stat='trb_per_g']/text()")
ast_per_g = data.xpath("//tbody/tr/td[@data-stat='ast_per_g']/text()")
stl_per_g = data.xpath("//tbody/tr/td[@data-stat='stl_per_g']/text()")
blk_per_g = data.xpath("//tbody/tr/td[@data-stat='blk_per_g']/text()")
tov_per_g = data.xpath("//tbody/tr/td[@data-stat='tov_per_g']/text()")
pf_per_g = data.xpath("//tbody/tr/td[@data-stat='pf_per_g']/text()")
pts_per_g = data.xpath("//tbody/tr/td[@data-stat='pts_per_g']/text()")

In [4]:
#combines all the columns
nba2019 = zip(player, 
              position, 
              age, 
              team, 
              games, 
              games_started, 
              mins_per_g, 
              fg_per_g, 
              fga_per_g, 
              fg_pct, 
              fg3_per_g, 
              fg3a_per_g, 
              fg3_pct, 
              fg2_per_g, 
              fg2a_per_g, 
              fg2_pct, 
              efg_pct, 
              ft_per_g, 
              fta_per_g, 
              ft_pct, 
              orb_per_g, 
              drb_per_g,
              trb_per_g,
              ast_per_g,
              stl_per_g,
              blk_per_g,
              tov_per_g,
              pf_per_g,
              pts_per_g)
#organizing our data structure to a pandas dataframe
df = pd.DataFrame(nba2019)

In [5]:
#renaming the column names 
df = df.rename(columns = {0:'player', 
                          1:'position', 
                          2:'age', 
                          3:'team', 
                          4:'games', 
                          5:'games_started', 
                          6:'mins_per_g', 
                          7:'fg_per_g', 
                          8:'fga_per_g', 
                          9:'fg_pct', 
                          10:'fg3_per_g', 
                          11:'fg3a_per_g', 
                          12:'fg3_pct', 
                          13:'fg2_per_g', 
                          14:'fg2a_per_g', 
                          15:'fg2_pct', 
                          16:'efg_pct', 
                          17:'ft_per_g', 
                          18:'fta_per_g', 
                          19:'ft_pct', 
                          20:'orb_per_g', 
                          21:'drb_per_g',
                          22:'trb_per_g',
                          23:'ast_per_g',
                          24:'stl_per_g',
                          25:'blk_per_g',
                          26:'tov_per_g',
                          27:'pf_per_g',
                          28:'pts_per_g'})
df.head()

,player,position,age,team,games,games_started,mins_per_g,fg_per_g,fga_per_g,fg_pct,...,ft_pct,orb_per_g,drb_per_g,trb_per_g,ast_per_g,stl_per_g,blk_per_g,tov_per_g,pf_per_g,pts_per_g
0,Álex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,.357,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,.222,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,.345,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,.595,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,.576,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9

In [8]:
df['age'] = pd.to_numeric(df['age'])
df['age'].fillna(0, inplace=True)

df['games'] = pd.to_numeric(df['games'])
df['games'].fillna(0, inplace=True)

df['games_started'] = pd.to_numeric(df['games_started'])
df['games_started'].fillna(0, inplace=True)

df['mins_per_g'] = pd.to_numeric(df['mins_per_g'])
df['mins_per_g'].fillna(0, inplace=True)

df['fg_per_g'] = pd.to_numeric(df['fg_per_g'])
df['fg_per_g'].fillna(0, inplace=True)

df['fga_per_g'] = pd.to_numeric(df['fga_per_g'])
df['fga_per_g'].fillna(0, inplace=True)

df['fg_pct'] = pd.to_numeric(df['fg_pct'])
df['fg_pct'].fillna(0, inplace=True)

df['fg3_per_g'] = pd.to_numeric(df['fg3_per_g'])
df['fg3_per_g'].fillna(0, inplace=True)

df['fg3a_per_g'] = pd.to_numeric(df['fg3a_per_g'])
df['fg3a_per_g'].fillna(0, inplace=True)

df['fg3_pct'] = pd.to_numeric(df['fg3_pct'])
df['fg3_pct'].fillna(0, inplace=True)

df['fg2_per_g'] = pd.to_numeric(df['fg2_per_g'])
df['fg2_per_g'].fillna(0, inplace=True)

df['fg2a_per_g'] = pd.to_numeric(df['fg2a_per_g'])
df['fg2a_per_g'].fillna(0, inplace=True)

df['fg2_pct'] = pd.to_numeric(df['fg2_pct'])
df['fg2_pct'].fillna(0, inplace=True)

df['efg_pct'] = pd.to_numeric(df['efg_pct'])
df['efg_pct'].fillna(0, inplace=True)

df['ft_per_g'] = pd.to_numeric(df['ft_per_g'])
df['ft_per_g'].fillna(0, inplace=True)

df['fta_per_g'] = pd.to_numeric(df['fta_per_g'])
df['fta_per_g'].fillna(0, inplace=True)

df['ft_pct'] = pd.to_numeric(df['ft_pct'])
df['ft_pct'].fillna(0, inplace=True)

df['orb_per_g'] = pd.to_numeric(df['orb_per_g'])
df['orb_per_g'].fillna(0, inplace=True)

df['drb_per_g'] = pd.to_numeric(df['drb_per_g'])
df['drb_per_g'].fillna(0, inplace=True)

df['trb_per_g'] = pd.to_numeric(df['trb_per_g'])
df['trb_per_g'].fillna(0, inplace=True)

df['ast_per_g'] = pd.to_numeric(df['ast_per_g'])
df['ast_per_g'].fillna(0, inplace=True)

df['stl_per_g'] = pd.to_numeric(df['stl_per_g'])
df['stl_per_g'].fillna(0, inplace=True)

df['blk_per_g'] = pd.to_numeric(df['blk_per_g'])
df['blk_per_g'].fillna(0, inplace=True)

df['tov_per_g'] = pd.to_numeric(df['tov_per_g'])
df['tov_per_g'].fillna(0, inplace=True)

df['pf_per_g'] = pd.to_numeric(df['pf_per_g'])
df['pf_per_g'].fillna(0, inplace=True)

df['pts_per_g'] = pd.to_numeric(df['pts_per_g'])
df['pts_per_g'].fillna(0, inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 708 entries, 0 to 707
Data columns (total 29 columns):
player           708 non-null object
position         708 non-null object
age              708 non-null int64
team             708 non-null object
games            708 non-null int64
games_started    708 non-null int64
mins_per_g       708 non-null float64
fg_per_g         708 non-null float64
fga_per_g        708 non-null float64
fg_pct           708 non-null float64
fg3_per_g        708 non-null float64
fg3a_per_g       708 non-null float64
fg3_pct          708 non-null float64
fg2_per_g        708 non-null float64
fg2a_per_g       708 non-null float64
fg2_pct          708 non-null float64
efg_pct          708 non-null float64
ft_per_g         708 non-null float64
fta_per_g        708 non-null float64
ft_pct           708 non-null float64
orb_per_g        708 non-null float64
drb_per_g        708 non-null float64
trb_per_g        708 non-null float64
ast_per_g        708 non-null float64
stl_per_g        708 non-null float64
blk_per_g        708 non-null float64
tov_per_g        708 non-null float64
pf_per_g         708 non-null float64
pts_per_g        708 non-null float64
dtypes: float64(23), int64(3), object(3)
memory usage: 160.5+ KB

In [43]:
stats.to_csv("stats.csv")

In [11]:
stats = df.drop_duplicates(subset=['player'], keep=False)

stats.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 444 entries, 0 to 704
Data columns (total 29 columns):
player           444 non-null object
position         444 non-null object
age              444 non-null int64
team             444 non-null object
games            444 non-null int64
games_started    444 non-null int64
mins_per_g       444 non-null float64
fg_per_g         444 non-null float64
fga_per_g        444 non-null float64
fg_pct           444 non-null float64
fg3_per_g        444 non-null float64
fg3a_per_g       444 non-null float64
fg3_pct          444 non-null float64
fg2_per_g        444 non-null float64
fg2a_per_g       444 non-null float64
fg2_pct          444 non-null float64
efg_pct          444 non-null float64
ft_per_g         444 non-null float64
fta_per_g        444 non-null float64
ft_pct           444 non-null float64
orb_per_g        444 non-null float64
drb_per_g        444 non-null float64
trb_per_g        444 non-null float64
ast_per_g        444 non-null float64
stl_per_g        444 non-null float64
blk_per_g        444 non-null float64
tov_per_g        444 non-null float64
pf_per_g         444 non-null float64
pts_per_g        444 non-null float64
dtypes: float64(23), int64(3), object(3)
memory usage: 104.1+ KB

In [35]:
position = stats.groupby(['position']).mean()

position.head()

,age,games,games_started,mins_per_g,fg_per_g,fga_per_g,fg_pct,fg3_per_g,fg3a_per_g,fg3_pct,...,ft_pct,orb_per_g,drb_per_g,trb_per_g,ast_per_g,stl_per_g,blk_per_g,tov_per_g,pf_per_g,pts_per_g
position,,,,,,,,,,,,,,,,,,,,,
C,26.144578,54.048193,27.156627,18.997590,3.513253,6.560241,0.522663,0.296386,0.925301,0.171867,...,0.664398,1.846988,4.109639,5.962651,1.430120,0.565060,0.867470,1.072289,2.168675,8.900000
PF,25.869048,48.666667,24.142857,17.861905,2.830952,6.140476,0.448702,0.785714,2.300000,0.278988,...,0.688024,0.936905,3.098810,4.026190,1.277381,0.496429,0.438095,0.916667,1.736905,7.702381
PG,25.956522,51.347826,25.467391,20.484783,3.492391,8.030435,0.414467,1.027174,2.913043,0.334391,...,0.721413,0.458696,2.226087,2.677174,3.667391,0.766304,0.226087,1.425000,1.623913,9.567391
SF,25.536232,48.289855,23.623188,20.586957,3.198551,7.092754,0.421507,0.966667,2.788406,0.310855,...,0.686826,0.720290,2.901449,3.624638,1.552174,0.689855,0.362319,0.953623,1.637681,8.742029
SG,25.215517,44.922414,19.767241,18.920690,3.205172,7.503448,0.411879,1.143103,3.285345,0.319638,...,0.678655,0.442241,1.984483,2.418966,1.802586,0.583621,0.216379,1.016379,1.496552,8.727586

In [39]:
position.reset_index(level=0, inplace=True)

position.columns

Index(['level_0', 'index', 'position', 'age', 'games', 'games_started',
       'mins_per_g', 'fg_per_g', 'fga_per_g', 'fg_pct', 'fg3_per_g',
       'fg3a_per_g', 'fg3_pct', 'fg2_per_g', 'fg2a_per_g', 'fg2_pct',
       'efg_pct', 'ft_per_g', 'fta_per_g', 'ft_pct', 'orb_per_g', 'drb_per_g',
       'trb_per_g', 'ast_per_g', 'stl_per_g', 'blk_per_g', 'tov_per_g',
       'pf_per_g', 'pts_per_g'],
      dtype='object')